// ============================================================
// NEXUS OS — Mock Data
// Realistic sample data for all modules
// ============================================================

import {
  Issue,
  IssueStatus,
  Priority,
  Doc,
  DocStatus,
  DocFormat,
  Certification,
  CertStatus,
} from "./types";

// ---- Issues ----

export const mockIssues: Issue[] = [
  {
    id: "i1",
    issueKey: "NEX-001",
    title: "Set up PostgreSQL database with Flyway migrations",
    description: "Initialize the PostgreSQL 16 database, configure Flyway, and create the initial migration scripts for all four tables (users, issues, docs, certifications).",
    status: IssueStatus.DONE,
    priority: Priority.HIGH,
    project: "Infrastructure",
    tags: ["database", "setup"],
    dueDate: "2026-03-20",
    createdBy: "user-1",
    createdAt: "2026-03-15T09:00:00Z",
    updatedAt: "2026-03-19T14:30:00Z",
  },
  {
    id: "i2",
    issueKey: "NEX-002",
    title: "Implement JWT authentication flow",
    description: "Build the complete auth flow: register, login, refresh token, logout. Use Spring Security with JWT Bearer tokens. Include role-based access control for ADMIN and VIEWER roles.",
    status: IssueStatus.IN_PROGRESS,
    priority: Priority.CRITICAL,
    project: "Auth",
    tags: ["security", "jwt", "backend"],
    dueDate: "2026-03-28",
    createdBy: "user-1",
    createdAt: "2026-03-16T10:00:00Z",
    updatedAt: "2026-03-27T11:00:00Z",
  },
  {
    id: "i3",
    issueKey: "NEX-003",
    title: "Design and build the sidebar navigation component",
    description: "Create a collapsible sidebar with navigation items for Dashboard, Issues, Docs, and Certifications. Include icon-only mode for smaller viewports.",
    status: IssueStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    project: "Frontend",
    tags: ["ui", "navigation", "layout"],
    dueDate: "2026-03-29",
    createdBy: "user-1",
    createdAt: "2026-03-18T08:00:00Z",
    updatedAt: "2026-03-27T16:00:00Z",
  },
  {
    id: "i4",
    issueKey: "NEX-004",
    title: "Build Tiptap rich-text editor with slash commands",
    description: "Integrate Tiptap editor with slash command menu supporting headings, lists, code blocks, tables, quotes, and callouts. Content serialized as JSON for PostgreSQL JSONB storage.",
    status: IssueStatus.TODO,
    priority: Priority.HIGH,
    project: "Docs Module",
    tags: ["editor", "tiptap", "frontend"],
    dueDate: "2026-04-05",
    createdBy: "user-1",
    createdAt: "2026-03-20T09:00:00Z",
    updatedAt: "2026-03-20T09:00:00Z",
  },
  {
    id: "i5",
    issueKey: "NEX-005",
    title: "Create certification CRUD REST endpoints",
    description: "Build the Spring Boot REST controller for certifications with full CRUD, file upload endpoint, and expiring certs query endpoint.",
    status: IssueStatus.TODO,
    priority: Priority.MEDIUM,
    project: "Cert Module",
    tags: ["backend", "api", "crud"],
    dueDate: "2026-04-08",
    createdBy: "user-1",
    createdAt: "2026-03-21T10:00:00Z",
    updatedAt: "2026-03-21T10:00:00Z",
  },
  {
    id: "i6",
    issueKey: "NEX-006",
    title: "Implement full-text search with pg_trgm",
    description: "Set up PostgreSQL tsvector indexing on docs table and enable pg_trgm extension for fuzzy search. Create the search API endpoint.",
    status: IssueStatus.BACKLOG,
    priority: Priority.MEDIUM,
    project: "Docs Module",
    tags: ["search", "database", "backend"],
    dueDate: null,
    createdBy: "user-1",
    createdAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
  },
  {
    id: "i7",
    issueKey: "NEX-007",
    title: "Build Kanban board with drag-and-drop",
    description: "Create the horizontal Kanban board view for issues with columns per status. Cards should be draggable between columns to update status.",
    status: IssueStatus.TODO,
    priority: Priority.MEDIUM,
    project: "Frontend",
    tags: ["ui", "kanban", "drag-drop"],
    dueDate: "2026-04-03",
    createdBy: "user-1",
    createdAt: "2026-03-22T14:00:00Z",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "i8",
    issueKey: "NEX-008",
    title: "Set up cert expiry email scheduler",
    description: "Configure Spring @Scheduled job to run daily at 8 AM, check for expiring certs, update statuses, and send Gmail SMTP notifications.",
    status: IssueStatus.BACKLOG,
    priority: Priority.LOW,
    project: "Cert Module",
    tags: ["scheduler", "email", "backend"],
    dueDate: null,
    createdBy: "user-1",
    createdAt: "2026-03-23T09:00:00Z",
    updatedAt: "2026-03-23T09:00:00Z",
  },
  {
    id: "i9",
    issueKey: "NEX-009",
    title: "Configure Docker Compose for all services",
    description: "Create docker-compose.yml with frontend, backend, and postgres services. Configure environment variables, volumes, and networking.",
    status: IssueStatus.IN_REVIEW,
    priority: Priority.HIGH,
    project: "Infrastructure",
    tags: ["docker", "devops", "setup"],
    dueDate: "2026-03-30",
    createdBy: "user-1",
    createdAt: "2026-03-17T08:00:00Z",
    updatedAt: "2026-03-26T10:00:00Z",
  },
  {
    id: "i10",
    issueKey: "NEX-010",
    title: "Implement dashboard overview page",
    description: "Build the main dashboard with stat cards, active issues feed, recent docs panel, and certification status alerts.",
    status: IssueStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    project: "Frontend",
    tags: ["ui", "dashboard"],
    dueDate: "2026-03-29",
    createdBy: "user-1",
    createdAt: "2026-03-24T10:00:00Z",
    updatedAt: "2026-03-28T08:00:00Z",
  },
  {
    id: "i11",
    issueKey: "NEX-011",
    title: "Add markdown split-pane editor view",
    description: "Create a split-pane view for docs: raw Markdown input on the left with live rendered preview on the right using react-markdown + remark-gfm.",
    status: IssueStatus.BACKLOG,
    priority: Priority.LOW,
    project: "Docs Module",
    tags: ["editor", "markdown", "frontend"],
    dueDate: null,
    createdBy: "user-1",
    createdAt: "2026-03-25T11:00:00Z",
    updatedAt: "2026-03-25T11:00:00Z",
  },
  {
    id: "i12",
    issueKey: "NEX-012",
    title: "Build issues list view with filters and sorting",
    description: "Create the list view for issues grouped by status with collapsible sections, filter bar (status, priority, project), and sort options.",
    status: IssueStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    project: "Frontend",
    tags: ["ui", "issues", "filters"],
    dueDate: "2026-03-30",
    createdBy: "user-1",
    createdAt: "2026-03-25T14:00:00Z",
    updatedAt: "2026-03-28T09:00:00Z",
  },
];

// ---- Docs ----

export const mockDocs: Doc[] = [
  {
    id: "d1",
    title: "Getting Started with NEXUS",
    content: null,
    markdown: "# Getting Started\n\nWelcome to NEXUS, your personal productivity OS...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.PUBLISHED,
    project: "NEXUS",
    topic: "Onboarding",
    tags: ["guide", "setup"],
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-26T14:00:00Z",
  },
  {
    id: "d2",
    title: "Database Schema Reference",
    content: null,
    markdown: "# Database Schema\n\n## Users Table\n\n| Column | Type | Description |\n...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.PUBLISHED,
    project: "NEXUS",
    topic: "Architecture",
    tags: ["database", "schema", "reference"],
    createdAt: "2026-03-16T09:00:00Z",
    updatedAt: "2026-03-25T11:00:00Z",
  },
  {
    id: "d3",
    title: "REST API Design Guidelines",
    content: null,
    markdown: "# API Design\n\nAll endpoints are prefixed with `/api`. Authentication via JWT...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.PUBLISHED,
    project: "NEXUS",
    topic: "Architecture",
    tags: ["api", "rest", "guidelines"],
    createdAt: "2026-03-17T11:00:00Z",
    updatedAt: "2026-03-24T16:00:00Z",
  },
  {
    id: "d4",
    title: "Tiptap Editor Integration Plan",
    content: null,
    markdown: "# Tiptap Integration\n\n## Extensions Required\n- StarterKit\n- Placeholder...",
    format: DocFormat.RICH,
    status: DocStatus.DRAFT,
    project: "NEXUS",
    topic: "Frontend",
    tags: ["editor", "tiptap", "planning"],
    createdAt: "2026-03-20T08:00:00Z",
    updatedAt: "2026-03-27T10:00:00Z",
  },
  {
    id: "d5",
    title: "Docker Deployment Runbook",
    content: null,
    markdown: "# Deployment Runbook\n\n## Prerequisites\n- Docker installed\n- Docker Compose v2...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.PUBLISHED,
    project: "NEXUS",
    topic: "DevOps",
    tags: ["docker", "deployment", "runbook"],
    createdAt: "2026-03-18T14:00:00Z",
    updatedAt: "2026-03-23T09:00:00Z",
  },
  {
    id: "d6",
    title: "Sprint Planning — Week 2",
    content: null,
    markdown: "# Sprint 2 Planning\n\n## Goals\n- Complete auth module\n- Start issues CRUD...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.DRAFT,
    project: "NEXUS",
    topic: "Planning",
    tags: ["sprint", "planning"],
    createdAt: "2026-03-22T09:00:00Z",
    updatedAt: "2026-03-28T08:00:00Z",
  },
  {
    id: "d7",
    title: "Arya Banking Auth Service Docs",
    content: null,
    markdown: "# Auth Service\n\nComprehensive documentation for the Arya Banking auth service...",
    format: DocFormat.MARKDOWN,
    status: DocStatus.PUBLISHED,
    project: "Arya Banking",
    topic: "Architecture",
    tags: ["auth", "microservices", "documentation"],
    createdAt: "2026-03-22T06:30:00Z",
    updatedAt: "2026-03-22T07:00:00Z",
  },
  {
    id: "d8",
    title: "UI Component Library Spec",
    content: null,
    markdown: "# Component Library\n\n## Design Tokens\n- Colors: Dark theme with Indigo accent...",
    format: DocFormat.RICH,
    status: DocStatus.DRAFT,
    project: "NEXUS",
    topic: "Frontend",
    tags: ["components", "design-system", "ui"],
    createdAt: "2026-03-26T10:00:00Z",
    updatedAt: "2026-03-28T09:00:00Z",
  },
];

// ---- Certifications ----

export const mockCertifications: Certification[] = [
  {
    id: "c1",
    name: "AWS Solutions Architect Associate",
    issuer: "Amazon Web Services",
    issuedDate: "2025-06-15",
    expiryDate: "2028-06-15",
    status: CertStatus.ACTIVE,
    reminderDays: 30,
    certFilePath: null,
    notes: "Passed with 842/1000. Covers core AWS services, best practices, and architectural patterns.",
    createdAt: "2025-06-16T10:00:00Z",
    updatedAt: "2025-06-16T10:00:00Z",
  },
  {
    id: "c2",
    name: "Certified Kubernetes Administrator",
    issuer: "Cloud Native Computing Foundation",
    issuedDate: "2025-09-10",
    expiryDate: "2026-04-10",
    status: CertStatus.EXPIRING_SOON,
    reminderDays: 30,
    certFilePath: null,
    notes: "CKA exam — performance-based, 66% passing score. Renewal required.",
    createdAt: "2025-09-11T08:00:00Z",
    updatedAt: "2026-03-10T08:00:00Z",
  },
  {
    id: "c3",
    name: "Oracle Certified Professional Java SE 21",
    issuer: "Oracle",
    issuedDate: "2026-01-20",
    expiryDate: null,
    status: CertStatus.ACTIVE,
    reminderDays: 30,
    certFilePath: null,
    notes: "Lifetime certification — no expiry. Covers Java 21 features including virtual threads, record patterns.",
    createdAt: "2026-01-21T09:00:00Z",
    updatedAt: "2026-01-21T09:00:00Z",
  },
  {
    id: "c4",
    name: "HashiCorp Terraform Associate",
    issuer: "HashiCorp",
    issuedDate: "2025-03-01",
    expiryDate: "2026-03-01",
    status: CertStatus.EXPIRED,
    reminderDays: 30,
    certFilePath: null,
    notes: "Expired — need to retake. Covers IaC concepts, Terraform workflow, state management.",
    createdAt: "2025-03-02T10:00:00Z",
    updatedAt: "2026-03-02T08:00:00Z",
  },
  {
    id: "c5",
    name: "Spring Professional Certification",
    issuer: "VMware / Broadcom",
    issuedDate: "2026-02-14",
    expiryDate: "2029-02-14",
    status: CertStatus.ACTIVE,
    reminderDays: 60,
    certFilePath: null,
    notes: "Covers Spring Framework 6, Spring Boot 3, Spring Security, Spring Data JPA.",
    createdAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "c6",
    name: "GitHub Actions Certification",
    issuer: "GitHub",
    issuedDate: "2025-11-05",
    expiryDate: "2026-05-05",
    status: CertStatus.EXPIRING_SOON,
    reminderDays: 45,
    certFilePath: null,
    notes: "CI/CD pipelines, workflow authoring, actions marketplace. Renew before May.",
    createdAt: "2025-11-06T09:00:00Z",
    updatedAt: "2026-03-20T08:00:00Z",
  },
];
